### ISSUE TITLE
Create a CONTRIBUTING.md and a (fixed) place for discussions

### ISSUE THREAD

**Issue by mputz86** [oswald2/AURIS#45]
Since probably most of the other contributors, like me, got into this project via your presentations at multiple Haskell-hackathons, it would maybe be a good idea to not only create some guidelines for contributions (to give a bar for code quality since most are maybe, like me, beginners and are rather producing confusing code which on top is not readable as well :) ) but maybe also to create a space (somewhere, Slack, Discord?) for discussions.
Especially the space for discussions and progress would be interesting since currently most of the stuff happens in the slack/discord spaces of the specific hackathon.

I just randomly file this issue, since I asked myself if you have been hacking on MuniHac (which I was unable to attend) and made any progress :).

Feel free to delete this if this does not fit :).

**Comment by oswald2** [comment]
Whoops completely missed this message. 

Ok, will do that. I am currently working on the system as I use it in a current project in the company for testing. Still it goes always different than planned...

**Comment by oswald2** [comment]
I created the CONTRIBUTING.md file and created a dedicated Discord server for questions, discussions and general communication: [Discord](https://discord.gg/jEdJxfVd)
